apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monkey-ingress
  namespace: monkey
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: monkey_socket
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"    
    traefik.ingress.kubernetes.io/http.middlewares.myapp.redirectscheme.scheme: "https"
    traefik.ingress.kubernetes.io/http.middlewares.myapp.redirectscheme.permanent: "true"
spec:
  tls:
    - hosts:
        - monkey.banano.cc
      secretName: monkey-banano-cc-server-secret
  rules:
    - host: monkey.banano.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nuxt-monkey-service
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: go-monkey-service
                port:
                  number: 5555
